# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	config.vm.define "node1" do |node|
		# Box Settings
		node.vm.box = "bento/ubuntu-16.04"
		node.vm.hostname = "node1"

		# Provider Settings
		node.vm.provider "virtualbox" do |vb|
		# Display the VirtualBox GUI when booting the machine
		vb.gui = false
		vb.name = "node1"
		# Customize the amount of memory on the VM:
		vb.memory = "512"
		end

		# Network Settings
		# slave.vm.network "forwarded_port", guest: 80, host: 8080
		# slave.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
		node.vm.network "private_network", ip: "192.168.33.11"
		# slave.vm.network "public_network"

		# Folder Settings
		# slave.vm.synced_folder "../data", "/vagrant_data"

		# Provision Settings
		# slave.vm.provision "shell", inline: <<-SHELL
		#   apt-get update
		#   apt-get install -y apache2
		# SHELL
	end
end
